<a href="https://colab.research.google.com/github/Satya-1729/Python_machine_learning/blob/main/creation_of_sequential_and_dense_function_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
# this code is wrong cause the concept here uses is opposite of what i learnt
#that is i added three neurons predicted value to form one value to the like in this code i did it
#in this eg after matrix multiplication each neuron has it predicted value like for neuron1 in layer 1 the predicted values are at column1 or 0 whatever
#for first row for of inputs from training example gives the value after multiplication by the weights of neuron1 like wise for second row in the
#x_train gives the second value like this upto all training examples this process goes for all three neurons and for all the rows or samples in the x_train
#now what i did is i added neuron1 first value and neuron2 first value and neuron 3 first value or in simple way row wise addition and makes it to nx1 matrix
#why i did this because i thought the value that second layer will take is of three inputs in the array that makes the big blunder out of it

# chatgpt explanation
'''What Went Wrong in Your Code
What You Did:

After computing the matrix multiplication for the layer, you summed up the outputs row-wise:
For example:
If the output matrix was
(
5
,
3
)
(5,3):
You added the outputs of all neurons for the first training example (row 1) and collapsed the row to a single value.
Repeated this for all rows, resulting in an output of shape
(
5
,
1
)
(5,1).
This essentially combined the outputs of all neurons into one value for each training example, which is not correct.
Why It's Wrong:

The second layer expects the outputs of all neurons individually as its inputs.
By summing the outputs row-wise, you lost the individual contributions of each neuron, which breaks the fundamental principle of a neural network layer.'''
import numpy as np


# Define the dataset as a NumPy array
shirt_data = np.array([
    ["Shirt_ID", "Brand", "Material", "Price", "Durability_Rating", "Style", "Comfort_Rating",
     "Sales_Last_Year", "Return_Rate", "Production_Cost", "Environmental_Impact", "Customer_Feedback",
     "Reliability_Score", "Popularity", "Market_Trend"],

    [1, "Zara", "Cotton", 25, 8, "Casual", 9, 15000, "3%", 12, "Medium", 4.5, 8.5, "High", "Increasing"],
    [2, "H&M", "Polyester", 20, 6, "Formal", 7, 12000, "5%", 8, "High", 4.0, 6.7, "Medium", "Stable"],
    [3, "Nike", "Dri-Fit", 30, 9, "Sports", 8, 18000, "2%", 15, "Low", 4.7, 8.9, "High", "Increasing"],
    [4, "Uniqlo", "Linen", 35, 7, "Casual", 8, 14000, "4%", 18, "Medium", 4.3, 7.5, "Medium", "Stable"],
    [5, "Levi’s", "Cotton", 40, 9, "Formal", 9, 16000, "3%", 20, "Low", 4.8, 8.9, "High", "Increasing"]
])

shirt_data

import pandas as pd
df = pd.DataFrame(shirt_data)
df

df1 = df.copy()
x_train = df1.iloc[1:,[3,4,6,9]].to_numpy()
x_train = x_train.astype(float)
print(x_train)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train = df1.iloc[1:,-1]

y_train = le.fit_transform(y_train)
y_train

#
def sigmoid(x):
  return 1/(1+np.exp(-x))
def my_dense(a,w,b):
  a = np.matmul(a,w)
  a = np.sum(a, axis=1)
  a = a.reshape(a.shape[0],1)
  a = a+b
  a = sigmoid(a)
  return a

def my_sequential(x,w1,b1,w2,b2):
  a1 = my_dense(x,w1,b1)
  a2 = my_dense(a1,w2,b2)
  return a2

w1 = np.random.rand(4,3)
print(w1,"\n\n\n\n")
b1 = np.random.rand(5,1)
print(b1,"\n\n\n\n")
w2 = np.random.rand(1,3)
print(w2,"\n\n\n\n")
b2 = np.random.rand(1,1)
print(b2,"\n\n\n\n")
y_pred = my_sequential(x_train,w1,b1,w2,b2)
y_pred


[[25.  8.  9. 12.]
 [20.  6.  7.  8.]
 [30.  9.  8. 15.]
 [35.  7.  8. 18.]
 [40.  9.  9. 20.]]
[[0.88811541 0.34968901 0.67976594]
 [0.46127365 0.29261855 0.24515167]
 [0.57091182 0.92472325 0.082982  ]
 [0.39794451 0.67926705 0.67238815]] 




[[0.10417354]
 [0.63210958]
 [0.40377216]
 [0.89029007]
 [0.61292779]] 




[[0.24129134 0.53709172 0.31140181]] 




[[0.43754138]] 






array([[0.82161478],
       [0.82161478],
       [0.82161478],
       [0.82161478],
       [0.82161478]])

In [2]:
np.zeros((4,)).dtype

dtype('float64')

In [27]:
def my_dense(a, w, b):
    # Matrix multiplication to compute weighted sums
    z = np.dot(a, w)  # Shape: (n_samples, units)

    # Broadcast and add bias
    z += b  # Bias should have shape (units,) or broadcastable

    return z  # Return the weighted sum (pre-activation)

# Random inputs and weights
w1 = np.random.rand(4, 3)  # Weights: 4 inputs, 3 neurons
print("Weights:\n", w1, "\n")

b1 = np.random.rand(3)  # Bias: 3 neurons
print("Bias:\n", b1, "\n")

x_train = np.random.rand(5, 4)  # 5 samples, 4 features
print("Input:\n", x_train, "\n")

# Compute dense layer output
dense_value = my_dense(x_train, w1, b1)
print("Dense Layer Output:\n", dense_value)


Weights:
 [[0.899373   0.33267789 0.99279434]
 [0.39285777 0.74028372 0.46405679]
 [0.91653184 0.54037698 0.43087828]
 [0.38095423 0.11699874 0.77923087]] 

Bias:
 [0.51593429 0.95391422 0.86364126] 

Input:
 [[0.1557841  0.05920808 0.03842804 0.87706577]
 [0.16444693 0.81680223 0.53091259 0.49623418]
 [0.62351317 0.52727375 0.76590795 0.4425832 ]
 [0.2214645  0.55041459 0.98608775 0.85331703]
 [0.23987353 0.51801839 0.36294233 0.0932416 ]] 

Dense Layer Output:
 [[1.04864508 1.17295214 1.74577328]
 [1.66036132 1.95823919 2.02138557]
 [2.15443175 2.01733615 2.40223417]
 [2.16020368 2.06774966 2.42874836]
 [1.30334659 1.62423025 1.571217  ]]


In [28]:
# correct version of code
#im just getting the concept wrong here the array of b i m adding row wise instead of
#adding column wise

print(x_train , "\n\n\n")
print(y_train ,"\n\n\n")

def sigmoid(x):
  return 1/(1+np.exp(-x))
def my_dense(a,w,b):
  a = np.matmul(a,w)

  a = a+ b
  print(a,"\n\n\n\n")

  a = sigmoid(a)
  return a

def my_sequential(x,w1,b1,w2,b2):
  a1 = my_dense(x,w1,b1)
  a2 = my_dense(a1,w2,b2)
  return a2

# the mistake that i was doing that adding the bias row wise instead of column wise
# and it leads to dimension error
w1 = np.random.rand(4,3)
# here shape of w suggests that there are 4features corresponding to them we have four weights
# and 3 is the column number inside the weight array this suggest number of neurons in the layer

print(w1,"\n\n\n\n")
b1 = np.random.rand(3)
# here bias has shape of 3 it means there are 3 neurons in the layer

print(b1,"\n\n\n\n")
w2 = np.random.rand(3,1)
print(w2,"\n\n\n\n")
b2 = np.random.rand(1)
print(b2,"\n\n\n\n")
y_pred = my_sequential(x_train,w1,b1,w2,b2)
print(y_pred)

b = np.zeros(5)
print(b)

for q in range (y_pred.shape[0]):
  if y_pred[q] > 0.5:
    b[q] = 1
  else:
    b[q] = 0

print(b)





[[0.1557841  0.05920808 0.03842804 0.87706577]
 [0.16444693 0.81680223 0.53091259 0.49623418]
 [0.62351317 0.52727375 0.76590795 0.4425832 ]
 [0.2214645  0.55041459 0.98608775 0.85331703]
 [0.23987353 0.51801839 0.36294233 0.0932416 ]] 



[0 1 0 1 0] 



[[0.154607   0.91699484 0.27053482]
 [0.2886422  0.21614697 0.92331988]
 [0.66726999 0.27473236 0.8561663 ]
 [0.27715429 0.77308432 0.26405668]] 




[0.29609013 0.51689262 0.21768219] 




[[0.14023845]
 [0.00047044]
 [0.40604121]] 




[0.06508022] 




[[0.60598981 1.36114669 0.57899107]
 [1.04907384 1.37372867 1.60192396]
 [1.17841432 1.75519343 1.64581818]
 [1.38369021 1.7695411  1.85538394]
 [0.75072106 1.02061913 1.09623307]] 




[[0.41639802]
 [0.50725866]
 [0.51311093]
 [0.52874182]
 [0.46504469]] 




[[0.60262101]
 [0.62416362]
 [0.62553547]
 [0.62918961]
 [0.61421023]]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
